[project]
name = "library-redis"
version = "0.1.0"
description = "A simple library management system using Redis"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.1",
    "flask-cors",
    "redis>=5.0.0",
    "pytest>=8.3.5"
]